**Run the following two cells before you begin.**

In [1]:
%autosave 10

Autosaving every 10 seconds


In [2]:
import pandas as pd
import numpy as np

______________________________________________________________________
**First, import your data set and define the sigmoid function.**
<details>
    <summary>Hint:</summary>
    The definition of the sigmoid is $f(x) = \frac{1}{1 + e^{-X}}$.
</details>

In [3]:
# Import the data set
df = pd.read_csv('/Users/priyanshutuli/Downloads/Project-Data-Set-Repository-master/Dataset/cleaned_data.csv')

In [4]:
# Define the sigmoid function
def sigmoid(x):
    return (1 / (1 + np.exp(-1 * x)))

**Now, create a train/test split (80/20) with `PAY_1` and `LIMIT_BAL` as features and `default payment next month` as values. Use a random state of 24.**

In [5]:
# Create a train/test split
X = df[['PAY_1','LIMIT_BAL']]
y = df['default payment next month']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 24)

______________________________________________________________________
**Next, import LogisticRegression, with the default options, but set the solver to `'liblinear'`.**

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr = LogisticRegression(solver = 'liblinear')

______________________________________________________________________
**Now, train on the training data and obtain predicted classes, as well as class probabilities, using the testing data.**

In [10]:
# Fit the logistic regression model on training data
lr.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [11]:
# Make predictions using `.predict()`
y_predict = lr.predict(X_test)

In [23]:
# Find class probabilities using `.predict_proba()`
sklearn_probabilities = lr.predict_proba(X_test)

______________________________________________________________________
**Then, pull out the coefficients and intercept from the trained model and manually calculate predicted probabilities. You'll need to add a column of 1s to your features, to multiply by the intercept.**

In [13]:
# Add column of 1s to features
X_test_new = np.hstack((X_test, np.ones((X_test.shape[0],1))))

In [14]:
# Get coefficients and intercepts from trained model
coefficients = lr.coef_
intercept = lr.intercept_

In [15]:
print(coefficients)
print(intercept)

[[ 8.27451187e-11 -6.80876727e-06]]
[-6.57647457e-11]


In [30]:
parameters = np.hstack((coefficients[0][0],coefficients[0][1],intercept))

In [31]:
print(X_test_new.shape)
print(parameters.shape)

(5333, 3)
(3,)


In [32]:
# Manually calculate predicted probabilities
values = np.sum(np.multiply(X_test_new, parameters),axis = 1)

In [33]:
probabilities = sigmoid(values)

In [34]:
print(probabilities)

[0.25173076 0.415703   0.20395547 ... 0.415703   0.17278502 0.33606565]


______________________________________________________________________
**Next, using a threshold of `0.5`, manually calculate predicted classes. Compare this to the class predictions output by scikit-learn.**

In [35]:
# Manually calculate predicted classes
def predicted_class(x):
    if x >= 0.5:
        return 1
    return 0

In [36]:
predicted_class_array = np.array([predicted_class(x) for x in probabilities])

In [37]:
# Compare to scikit-learn's predicted classes
predicted_class_array[predicted_class_array == lr.predict(X_test)]

array([0, 0, 0, ..., 0, 0, 0])

______________________________________________________________________
**Finally, calculate ROC AUC using both scikit-learn's predicted probabilities, and your manually predicted probabilities, and compare.**

In [38]:
# Use scikit-learn's predicted probabilities to calculate ROC AUC
from sklearn.metrics import roc_auc_score

In [39]:
roc_auc_score(y_test, sklearn_probabilities[:,1])

0.627207450280691

In [40]:
# Use manually calculated predicted probabilities to calculate ROC AUC
roc_auc_score(y_test, probabilities)

0.627207450280691